/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BottomButtonGroup: typeof import('./../components/bottom-button-group/bottom-button-group.vue')['default']
    ButtonGroupHolder: typeof import('./../components/button-group-holder/button-group-holder.vue')['default']
    CircularProgress: typeof import('./../components/circular-progress/circular-progress.vue')['default']
    CommentInput: typeof import('./../components/comment-input/comment-input.vue')['default']
    Empty: typeof import('./../components/empty/empty.vue')['default']
    Form: typeof import('./../components/form/form.vue')['default']
    FormItem: typeof import('./../components/form-item/form-item.vue')['default']
    IconFont: typeof import('./../components/icon-font/icon-font.vue')['default']
    Input: typeof import('./../components/input/input.vue')['default']
    Label: typeof import('./../components/label/label.vue')['default']
    ListData: typeof import('./../components/list-data/list-data.vue')['default']
    LoadingView: typeof import('./../components/loading-view/loading-view.vue')['default']
    MediaUploader: typeof import('./../components/media-uploader/media-uploader.vue')['default']
    Modal: typeof import('./../components/modal/modal.vue')['default']
    NavBar: typeof import('./../components/nav-bar/nav-bar.vue')['default']
    Popup: typeof import('./../components/popup/popup.vue')['default']
    Progress: typeof import('./../components/progress/progress.vue')['default']
    Radio: typeof import('./../components/radio/radio.vue')['default']
    SearchBar: typeof import('./../components/search-bar/search-bar.vue')['default']
    TabBar: typeof import('./../components/tab-bar/tab-bar.vue')['default']
    UaMarkdown: typeof import('./../components/ua-markdown/ua-markdown.vue')['default']
  }
}
