interface SpeakerOption {
  label: string
  value: string
  scene: string
  name: string
  voiceType: string
  language: string[]
  abilities: string[]
}

export const speakerOptions: SpeakerOption[] = [
  {
    label: '黑猫侦探社咪仔-1',
    value: 'zh_female_mizaitongxue_v2_saturn_bigtts',
    scene: '视频配音',
    name: '黑猫侦探社咪仔-1',
    voiceType: 'zh_female_mizaitongxue_v2_saturn_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '黑猫侦探社咪仔-2',
    value: 'zh_male_dayixiansheng_v2_saturn_bigtts',
    scene: '视频配音',
    name: '黑猫侦探社咪仔-2',
    voiceType: 'zh_male_dayixiansheng_v2_saturn_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '刘飞',
    value: 'zh_male_liufei_v2_saturn_bigtts',
    scene: '通用场景',
    name: '刘飞',
    voiceType: 'zh_male_liufei_v2_saturn_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '潇磊',
    value: 'zh_male_xiaolei_v2_saturn_bigtts',
    scene: '通用场景',
    name: '潇磊',
    voiceType: 'zh_male_xiaolei_v2_saturn_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: 'Vivi 2.0',
    value: 'zh_female_vv_uranus_bigtts',
    scene: '通用场景',
    name: 'Vivi 2.0',
    voiceType: 'zh_female_vv_uranus_bigtts',
    language: ['中文', '日文', '印尼', '墨西哥西班牙语'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '小何 2.0',
    value: 'zh_female_xiaohe_uranus_bigtts',
    scene: '通用场景',
    name: '小何 2.0',
    voiceType: 'zh_female_xiaohe_uranus_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '云舟 2.0',
    value: 'zh_male_m191_uranus_bigtts',
    scene: '通用场景',
    name: '云舟 2.0',
    voiceType: 'zh_male_m191_uranus_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '小天 2.0',
    value: 'zh_male_taocheng_uranus_bigtts',
    scene: '通用场景',
    name: '小天 2.0',
    voiceType: 'zh_male_taocheng_uranus_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '刘飞 2.0',
    value: 'zh_male_liufei_uranus_bigtts',
    scene: '通用场景',
    name: '刘飞 2.0',
    voiceType: 'zh_male_liufei_uranus_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '魅力苏菲 2.0',
    value: 'zh_male_sophie_uranus_bigtts',
    scene: '通用场景',
    name: '魅力苏菲 2.0',
    voiceType: 'zh_male_sophie_uranus_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '清新女声 2.0',
    value: 'zh_female_qingxinnvsheng_uranus_bigtts',
    scene: '通用场景',
    name: '清新女声 2.0',
    voiceType: 'zh_female_qingxinnvsheng_uranus_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '知性灿灿 2.0',
    value: 'zh_female_cancan_uranus_bigtts',
    scene: '角色扮演',
    name: '知性灿灿 2.0',
    voiceType: 'zh_female_cancan_uranus_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '撒娇学妹 2.0',
    value: 'zh_female_sajiaoxuemei_uranus_bigtts',
    scene: '角色扮演',
    name: '撒娇学妹 2.0',
    voiceType: 'zh_female_sajiaoxuemei_uranus_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '甜美小源 2.0',
    value: 'zh_female_tianmeixiaoyuan_uranus_bigtts',
    scene: '通用场景',
    name: '甜美小源 2.0',
    voiceType: 'zh_female_tianmeixiaoyuan_uranus_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '甜美桃子 2.0',
    value: 'zh_female_tianmeitaozi_uranus_bigtts',
    scene: '通用场景',
    name: '甜美桃子 2.0',
    voiceType: 'zh_female_tianmeitaozi_uranus_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '爽快思思 2.0',
    value: 'zh_female_shuangkuaisisi_uranus_bigtts',
    scene: '通用场景',
    name: '爽快思思 2.0',
    voiceType: 'zh_female_shuangkuaisisi_uranus_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '佩奇猪 2.0',
    value: 'zh_female_peiqi_uranus_bigtts',
    scene: '视频配音',
    name: '佩奇猪 2.0',
    voiceType: 'zh_female_peiqi_uranus_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '邻家女孩 2.0',
    value: 'zh_female_linjianvhai_uranus_bigtts',
    scene: '通用场景',
    name: '邻家女孩 2.0',
    voiceType: 'zh_female_linjianvhai_uranus_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '少年梓辛/Brayan 2.0',
    value: 'zh_male_shaonianzixin_uranus_bigtts',
    scene: '通用场景',
    name: '少年梓辛/Brayan 2.0',
    voiceType: 'zh_male_shaonianzixin_uranus_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '猴哥 2.0',
    value: 'zh_male_sunwukong_uranus_bigtts',
    scene: '视频配音',
    name: '猴哥 2.0',
    voiceType: 'zh_male_sunwukong_uranus_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: 'Tina老师 2.0',
    value: 'zh_female_yingyujiaoxue_uranus_bigtts',
    scene: '教育场景',
    name: 'Tina老师 2.0',
    voiceType: 'zh_female_yingyujiaoxue_uranus_bigtts',
    language: ['中文', '英式英语'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '暖阳女声 2.0',
    value: 'zh_female_kefunvsheng_uranus_bigtts',
    scene: '客服场景',
    name: '暖阳女声 2.0',
    voiceType: 'zh_female_kefunvsheng_uranus_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '儿童绘本 2.0',
    value: 'zh_female_xiaoxue_uranus_bigtts',
    scene: '有声阅读',
    name: '儿童绘本 2.0',
    voiceType: 'zh_female_xiaoxue_uranus_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '大壹 2.0',
    value: 'zh_male_dayi_uranus_bigtts',
    scene: '视频配音',
    name: '大壹 2.0',
    voiceType: 'zh_male_dayi_uranus_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '黑猫侦探社咪仔 2.0',
    value: 'zh_female_mizai_uranus_bigtts',
    scene: '视频配音',
    name: '黑猫侦探社咪仔 2.0',
    voiceType: 'zh_female_mizai_uranus_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '鸡汤女 2.0',
    value: 'zh_female_jitangnv_uranus_bigtts',
    scene: '视频配音',
    name: '鸡汤女 2.0',
    voiceType: 'zh_female_jitangnv_uranus_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '魅力女友 2.0',
    value: 'zh_female_meilinvyou_uranus_bigtts',
    scene: '通用场景',
    name: '魅力女友 2.0',
    voiceType: 'zh_female_meilinvyou_uranus_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '流畅女声 2.0',
    value: 'zh_female_liuchangnv_uranus_bigtts',
    scene: '视频配音',
    name: '流畅女声 2.0',
    voiceType: 'zh_female_liuchangnv_uranus_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '儒雅逸辰 2.0',
    value: 'zh_male_ruyayichen_uranus_bigtts',
    scene: '视频配音',
    name: '儒雅逸辰 2.0',
    voiceType: 'zh_male_ruyayichen_uranus_bigtts',
    language: ['中文'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: 'Tim',
    value: 'en_male_tim_uranus_bigtts',
    scene: '多语种',
    name: 'Tim',
    voiceType: 'en_male_tim_uranus_bigtts',
    language: ['美式英语'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: 'Dacey',
    value: 'en_female_dacey_uranus_bigtts',
    scene: '多语种',
    name: 'Dacey',
    voiceType: 'en_female_dacey_uranus_bigtts',
    language: ['美式英语'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: 'Stokie',
    value: 'en_female_stokie_uranus_bigtts',
    scene: '多语种',
    name: 'Stokie',
    voiceType: 'en_female_stokie_uranus_bigtts',
    language: ['美式英语'],
    abilities: ['情感变化', '指令遵循', 'ASMR'],
  },
  {
    label: '可爱女生',
    value: 'saturn_zh_female_keainvsheng_tob',
    scene: '角色扮演',
    name: '可爱女生',
    voiceType: 'saturn_zh_female_keainvsheng_tob',
    language: ['中文'],
    abilities: ['指令遵循', 'COT/QA功能'],
  },
  {
    label: '调皮公主',
    value: 'saturn_zh_female_tiaopigongzhu_tob',
    scene: '角色扮演',
    name: '调皮公主',
    voiceType: 'saturn_zh_female_tiaopigongzhu_tob',
    language: ['中文'],
    abilities: ['指令遵循', 'COT/QA功能'],
  },
  {
    label: '爽朗少年',
    value: 'saturn_zh_male_shuanglangshaonian_tob',
    scene: '角色扮演',
    name: '爽朗少年',
    voiceType: 'saturn_zh_male_shuanglangshaonian_tob',
    language: ['中文'],
    abilities: ['指令遵循', 'COT/QA功能'],
  },
  {
    label: '天才同桌',
    value: 'saturn_zh_male_tiancaitongzhuo_tob',
    scene: '角色扮演',
    name: '天才同桌',
    voiceType: 'saturn_zh_male_tiancaitongzhuo_tob',
    language: ['中文'],
    abilities: ['指令遵循', 'COT/QA功能'],
  },
  {
    label: '知性灿灿',
    value: 'saturn_zh_female_cancan_tob',
    scene: '角色扮演',
    name: '知性灿灿',
    voiceType: 'saturn_zh_female_cancan_tob',
    language: ['中文'],
    abilities: ['指令遵循', 'COT/QA功能'],
  },
  {
    label: '轻盈朵朵 2.0',
    value: 'saturn_zh_female_qingyingduoduo_cs_tob',
    scene: '客服场景',
    name: '轻盈朵朵 2.0',
    voiceType: 'saturn_zh_female_qingyingduoduo_cs_tob',
    language: ['中文'],
    abilities: ['指令遵循'],
  },
  {
    label: '温婉珊珊 2.0',
    value: 'saturn_zh_female_wenwanshanshan_cs_tob',
    scene: '客服场景',
    name: '温婉珊珊 2.0',
    voiceType: 'saturn_zh_female_wenwanshanshan_cs_tob',
    language: ['中文'],
    abilities: ['指令遵循'],
  },
  {
    label: '热情艾娜 2.0',
    value: 'saturn_zh_female_reqingaina_cs_tob',
    scene: '客服场景',
    name: '热情艾娜 2.0',
    voiceType: 'saturn_zh_female_reqingaina_cs_tob',
    language: ['中文'],
    abilities: ['指令遵循'],
  },
]